#### Importando la libreria de Pytorch

In [0]:
import torch
import numpy as np
import pandas as pd


#### Tensores

In [31]:
tensor_a = torch.ones(2, 2)
tensor_a 

tensor([[1., 1.],
        [1., 1.]])

#### Declaración del tensor b (uso de Tensor) + método uniform.


In [32]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)
print(tensor_b)

tensor([[1.8928e-35, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])
tensor([[0.4574, 0.5541],
        [0.7252, 0.3798]])


#### Rand es para generar tensores entre 0 y 1

In [33]:
tensor_c = torch.rand(2, 2)
tensor_c


tensor([[0.5968, 0.8433],
        [0.7056, 0.2284]])

In [34]:
result = tensor_a + tensor_b
print(result)

tensor([[1.4574, 1.5541],
        [1.7252, 1.3798]])


#### Metodo para variar las dimensiones de los tensores.


In [35]:
result.shape
reshaped = result.view(1, 4)
print(reshaped)


tensor([[1.4574, 1.5541, 1.7252, 1.3798]])


#### Creación de tensor con valores que nosotros asignmaos. Con metodo storage podemos saber de que manera se esta almacenando.

In [36]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)

points.storage()

tensor([[1., 2.],
        [3., 4.]])


 1.0
 2.0
 3.0
 4.0
[torch.FloatStorage of size 4]

#### Podemos transponer el tensor.

In [37]:
points_transposition = points.t()
points_transposition

tensor([[1., 3.],
        [2., 4.]])

#### Con el metodo unsqueeze para agregar dimensiones

In [38]:
tensor_x = torch.tensor([1, 2, 3, 4])
print(tensor_x)
torch.unsqueeze(tensor_x, 0)


tensor([1, 2, 3, 4])


tensor([[1, 2, 3, 4]])

#### Crear tensores a partir de arreglos.

In [39]:
numpyArray = np.random.randn(2, 2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[ 1.2709,  0.2666],
        [-0.5186,  1.9076]], dtype=torch.float64)

### Representacion de datos con tensores (clase 3).







In [40]:
print(from_numpy)
torch.mean(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim = 0))
print(torch.mean(from_numpy, dim = 1))


tensor([[ 1.2709,  0.2666],
        [-0.5186,  1.9076]], dtype=torch.float64)
tensor(0.7316, dtype=torch.float64)
tensor([0.3761, 1.0871], dtype=torch.float64)
tensor([0.7687, 0.6945], dtype=torch.float64)


In [41]:
torch.std(from_numpy, dim = 1)


tensor([0.7101, 1.7156], dtype=torch.float64)

In [0]:
torch.save(from_numpy, 'tensor.t')

In [43]:
load = torch.load('tensor.t')
load

tensor([[ 1.2709,  0.2666],
        [-0.5186,  1.9076]], dtype=torch.float64)

#### Usando Pandas incorporamos un dataset

In [44]:
url = 'https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv'
dataframe = pd.read_csv(url) #Con pd.read_csv(y la variable que contiene el url), podremos leer el data set
dataframe 


Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [45]:
dataframe.columns #Si queremos ver columnas


Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [69]:
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot', 'Skill Moves']].dropna(axis = 0, how = 'any')

columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [54]:
data = players[:, 0:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18207, 4]))

In [71]:
target = players[:, 1]
target, target.shape

mean = torch.mean(data, dim = 0)
mean



tensor([4.6699,    nan,    nan,    nan])

In [72]:
std = torch.std(data, dim = 0)
std

tensor([4.6699,    nan,    nan,    nan])